<?php
declare(strict_types=1);

// Salesforce SDK utility registration

require_once __DIR__ . '/../core/UtilityType.php';
require_once __DIR__ . '/Clean.php';
require_once __DIR__ . '/Done.php';
require_once __DIR__ . '/MakeError.php';
require_once __DIR__ . '/FeatureAdd.php';
require_once __DIR__ . '/FeatureHook.php';
require_once __DIR__ . '/FeatureInit.php';
require_once __DIR__ . '/Fetcher.php';
require_once __DIR__ . '/MakeFetchDef.php';
require_once __DIR__ . '/MakeContext.php';
require_once __DIR__ . '/MakeOptions.php';
require_once __DIR__ . '/MakeRequest.php';
require_once __DIR__ . '/MakeResponse.php';
require_once __DIR__ . '/MakeResult.php';
require_once __DIR__ . '/MakePoint.php';
require_once __DIR__ . '/MakeSpec.php';
require_once __DIR__ . '/MakeUrl.php';
require_once __DIR__ . '/Param.php';
require_once __DIR__ . '/PrepareAuth.php';
require_once __DIR__ . '/PrepareBody.php';
require_once __DIR__ . '/Graphql.php';
require_once __DIR__ . '/PrepareHeaders.php';
require_once __DIR__ . '/PrepareMethod.php';
require_once __DIR__ . '/PrepareParams.php';
require_once __DIR__ . '/PreparePath.php';
require_once __DIR__ . '/PrepareQuery.php';
require_once __DIR__ . '/ResultBasic.php';
require_once __DIR__ . '/ResultBody.php';
require_once __DIR__ . '/ResultHeaders.php';
require_once __DIR__ . '/TransformRequest.php';
require_once __DIR__ . '/TransformResponse.php';

SalesforceUtility::setRegistrar(function (SalesforceUtility $u): void {
    $u->clean = [SalesforceClean::class, 'call'];
    $u->done = [SalesforceDone::class, 'call'];
    $u->make_error = [SalesforceMakeError::class, 'call'];
    $u->feature_add = [SalesforceFeatureAdd::class, 'call'];
    $u->feature_hook = [SalesforceFeatureHook::class, 'call'];
    $u->feature_init = [SalesforceFeatureInit::class, 'call'];
    $u->fetcher = [SalesforceFetcher::class, 'call'];
    $u->make_fetch_def = [SalesforceMakeFetchDef::class, 'call'];
    $u->make_context = [SalesforceMakeContext::class, 'call'];
    $u->make_options = [SalesforceMakeOptions::class, 'call'];
    $u->make_request = [SalesforceMakeRequest::class, 'call'];
    $u->make_response = [SalesforceMakeResponse::class, 'call'];
    $u->make_result = [SalesforceMakeResult::class, 'call'];
    $u->make_point = [SalesforceMakePoint::class, 'call'];
    $u->make_spec = [SalesforceMakeSpec::class, 'call'];
    $u->make_url = [SalesforceMakeUrl::class, 'call'];
    $u->param = [SalesforceParam::class, 'call'];
    $u->prepare_auth = [SalesforcePrepareAuth::class, 'call'];
    $u->prepare_body = [SalesforcePrepareBody::class, 'call'];
    $u->prepare_headers = [SalesforcePrepareHeaders::class, 'call'];
    $u->prepare_method = [SalesforcePrepareMethod::class, 'call'];
    $u->prepare_params = [SalesforcePrepareParams::class, 'call'];
    $u->prepare_path = [SalesforcePreparePath::class, 'call'];
    $u->prepare_query = [SalesforcePrepareQuery::class, 'call'];
    $u->graphql_body = [SalesforceGraphql::class, 'body'];
    $u->graphql_errors = [SalesforceGraphql::class, 'errors'];
    $u->result_basic = [SalesforceResultBasic::class, 'call'];
    $u->result_body = [SalesforceResultBody::class, 'call'];
    $u->result_headers = [SalesforceResultHeaders::class, 'call'];
    $u->transform_request = [SalesforceTransformRequest::class, 'call'];
    $u->transform_response = [SalesforceTransformResponse::class, 'call'];
});
